name: CSM backend

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: |
          touch .env
          echo "${{ secrets.PROD_ENV_FILE }}" > .env
      - run: pm2 restart BackendAPI || pm2 start npm --name "BackendAPI" -- start
 
  # deploy:
  #   needs: build
  #   runs-on: self-hosted 
  #   steps:
  #     - name: Pull image from docker hub
  #       run: docker pull csmaviation/csmbackend:latest 
  #     - name: Stop and remove existing container
  #       run: |
  #         docker stop nodejs-app-container || true
  #         docker rm nodejs-app-container || true
  #       continue-on-error: true
  #     - name: Run Docker Container
  #       run: |
  #         docker run -d --init --name nodejs-app-container \
  #           -p 5000:5000 \
  #           -e MONGO_PASSWORD='${{ secrets.MONGO_USER_PASSWORD }}' \
  #           csmaviation/csmbackend
  #     - name: Prune unused Docker resources
  #       run: docker system prune -f
