name: CSM backend

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    
      - name: Build Docker Image
        run: docker build -t csmaviation/csmbackend  .
      - name: Publish Image to docker hub
        run: docker push csmaviation/csmbackend:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull csmaviation/csmbackend:latest 
      - name: Stop and remove existing container
        run: |
          docker stop nodejs-app-container || true
          docker rm nodejs-app-container || true
        continue-on-error: true
      - name: Run Docker Container
        run: |
          docker run -d --init --name nodejs-app-container \
            -p 5000:5000 \
            -e MONGO_PASSWORD='${{ secrets.MONGO_USER_PASSWORD }}' \
            csmaviation/csmbackend
      - name: Prune unused Docker resources
        run: docker system prune -f